import { analyzeActivityEvent } from "./activityAnalysisEngine.js";
import { enrichMultimodalCapture } from "./multimodalCaptureService.js";
import { createSessionSummary, detectSmartSessions } from "./sessionDetectionEngine.js";
import { analyzeProductivity } from "./productivityAnalysisEngine.js";
import { buildMemoryClusters, buildResurfacingNotifications, buildResurfacingSuggestions } from "./memoryResurfacingEngine.js";

function eventKind(type, intent) {
  if (type === "screenshot") return "screenshot";
  if (type === "voice-snippet") return "voice";
  if (type === "focus-session") return "focus";
  if (intent === "idea-burst") return "idea";
  if (intent === "research") return "insight";
  if (intent === "planning") return "timeline";
  return "memory";
}

function memoryBody(enriched) {
  return [
    enriched.summary,
    enriched.context ? `Context: ${enriched.context}` : "",
    `AI detected intent: ${enriched.intent}. Productivity ${enriched.productivityScore}%, focus ${enriched.focusScore}%, emotion ${enriched.emotionalScore}%.`,
  ]
    .filter(Boolean)
    .join("\n")
    .slice(0, 980);
}

export async function runAutonomousCapture({ event, memories = [], relationships = [] }) {
  const base = analyzeActivityEvent(event, memories);
  const enriched = await enrichMultimodalCapture(event, base);
  const resurfacing = buildResurfacingSuggestions(memories, relationships, enriched).slice(0, 4);
  const relatedMemories = resurfacing.map((item) => item.id);
  const session = event.type === "focus-session" || event.durationMs
    ? createSessionSummary([{ ...enriched, durationMs: event.durationMs }])
    : null;

  const shouldSave = enriched.shouldCapture && enriched.confidence >= 50;
  const entryPayload = shouldSave
    ? {
        kind: eventKind(enriched.type, enriched.intent),
        type: eventKind(enriched.type, enriched.intent),
        title: enriched.title,
        body: memoryBody(enriched),
        meta: `${enriched.source} · ${enriched.intent}`,
        tags: enriched.tags.join(", "),
        summary: enriched.summary,
        location: event.location || null,
        media: enriched.media || null,
        source: "autonomous-capture",
        metadata: {
          ...(enriched.metadata || {}),
          autoGenerated: true,
          captureSource: enriched.source,
          captureType: enriched.type,
          intent: enriched.intent,
          emotionalScore: enriched.emotionalScore,
          productivityScore: enriched.productivityScore,
          focusScore: enriched.focusScore,
          replayPriorityScore: enriched.replayPriorityScore,
          confidence: enriched.confidence,
          privacyLevel: enriched.privacyLevel,
          relatedMemories,
          session,
        },
      }
    : null;

  return {
    captured: shouldSave,
    analysis: enriched,
    session,
    relatedMemories: resurfacing,
    entryPayload,
    message: shouldSave
      ? `${enriched.title} became an autonomous memory.`
      : "Activity signal analyzed without saving because it was not meaningful enough yet.",
  };
}

export function buildAutonomousCaptureDashboard({ memories = [], relationships = [] }) {
  const productivity = analyzeProductivity(memories);
  const sessions = detectSmartSessions(memories);
  const clusters = buildMemoryClusters(memories, relationships);
  const resurfacing = buildResurfacingSuggestions(memories, relationships).slice(0, 5);
  const autonomousMemories = memories.filter((memory) =>
    memory.metadata?.captureSource ||
    memory.metadata?.autoGenerated ||
    /capture|ocr|voice|clipboard/i.test(memory.metadata?.source || "") ||
    memory.tags?.includes("auto-capture"),
  );

  return {
    status: {
      mode: "permission-based-web",
      active: true,
      privacy: "Only NeuroNest activity and user-approved clipboard/screenshot/voice captures are processed.",
      capturedCount: autonomousMemories.length,
      queueDepth: 0,
      lastCaptureAt: autonomousMemories[0]?.createdAt || null,
    },
    indicators: [
      { label: "Passive engine", value: 96, body: "Listening for meaningful in-app activity." },
      { label: "Session detector", value: Math.min(98, 60 + sessions.length * 8), body: `${sessions.length} smart sessions detected.` },
      { label: "Resurfacing", value: Math.min(98, 58 + resurfacing.length * 7), body: `${resurfacing.length} memories ready to resurface.` },
      { label: "Privacy guard", value: 100, body: "Permission-gated capture controls are active." },
    ],
    productivity,
    sessions,
    clusters,
    resurfacing,
    notifications: buildResurfacingNotifications(memories, relationships),
    recentCaptures: autonomousMemories.slice(0, 6).map((memory) => ({
      id: memory.id,
      title: memory.title,
      summary: memory.summary,
      type: memory.type,
      confidence: memory.metadata?.confidence || memory.aiScore || 72,
      createdAt: memory.createdAt,
    })),
  };
}
